language: php

php:
  - 8.1
  - 8.2
  - 8.3

services:
  - mysql
  - postgresql

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'

  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 8.1
      env: PHPCS=1 DEFAULT=0

    - php: 8.1
      env: STATIC_ANALYSIS=1 DEFAULT=0

    - php: 8.1
      env: PREFER_LOWEST=1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.4 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

script:
  - |
    if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.4 ]]; then
      mkdir -p build/logs
      vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.4 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then vendor/bin/phpstan analyse src -l 5; fi

after_success:
  - |
    if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 8.1 ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      chmod +x php-coveralls.phar
      ./php-coveralls.phar
    fi
notifications:
  email: false
